### ISSUE TITLE
Oxygen atomic mass

### ISSUE THREAD

**Issue by ferdymercury** [Metex/NISTConst#2]
This constant would be also helpful, in case you may want to add it in future releases:

#define OXYGEN16AMU 15.9994                                   ///<Atomic mass of O-16 in u
https://physics.nist.gov/PhysRefData/Handbook/Tables/oxygentable1.htm

**Comment by DrGrafil** [comment]
I have actually been considering adding common isotopes mass to the constants soon.  One of the key issues is that there is no definitive source 

15.99491461956 u National Nuclear Data Center (US based) http://www.nndc.bnl.gov/masses/mass.mas12
15.99491461960 u International Atomic Energy Agency https://www-nds.iaea.org/amdc/ame2016/mass16.txt
And the models used for nuclear data structures has another number I cant really find the source for.
Unfortunately NIST isn't a good place to look for atomic numbers.

I find it strange that the US based NNDC is pointing to an older version of the compiled list that the IAEA has. I might eventually use the recent numbers done by IAEA however I would like to first know why the NNDC has picked an older data set to use. Once that is sorted out expect an update.

**Comment by DrGrafil** [comment]
@ferdymercury After much discussion I decided to go with most recent update from the International Atomic Energy Agency. I ended up deciding to essential dump the entire database into a header file in a separate project [IsotopeConst](https://github.com/Metex/IsotopeConst). I would include it in NISTConst but given the number of isotopes, 3000+, and the difficulty in deciding what isotopes were common it made more sense to just be through and have all isotopes in a separate file.

**Comment by ferdymercury** [comment]
That is excellent, thanks for your work. Much appreciated.

**Comment by ferdymercury** [comment]
Just a side comment, have you ever considered using https://www.boost.org/doc/libs/1_68_0/doc/html/boost_units/Examples.html#boost_units.Examples.QuantityExample ?

Could be helpful to have the user decide what units to actually use. But might be too much overhead for so many constants.

**Comment by DrGrafil** [comment]
@ferdymercury I have considered doing something like that with unit conversion however I at this point have zero trust in any unit conversion package. They all seem to have large errors in them when you start converting extremely large or small numbers. An example being googles unit conversion. Searching: [1 fermi to femtometer](https://www.google.com/search?q=1+fermi+to+femtometer) brings up a 1=0.990032 where it should be 1 to 1.

This might be due to the fact that under the hood everything is set in terms of meters and inches. In the previous example it is probably dividing by 10^15 to get to meters and then multiplying by 10^15 to get to femtometers which leads to a rounding error.
